(use-modules (brassica gay event)
             (ice-9 match))

(define sample
  (make-gay-event 'protention
                  #:color '((domain strategy)
                            (phase protention)
                            (role generator)
                            (sensitivity internal))
                  #:refs '((observation "obs-1"))
                  #:body '((claim "A test protention")
                           (confidence 0.5))
                  #:feedback '((requested (contradiction evidence)))))

(unless (gay-event? sample)
  (error "sample is not gay-event" sample))
(unless (valid-gay-event? sample)
  (error "sample is not valid" sample))
(unless (eq? (gay-event-kind sample) 'protention)
  (error "bad kind" sample))
(unless (equal? (gay-event-color-ref sample 'domain) 'strategy)
  (error "bad color lookup" sample))
(unless (equal? (gay-event-ref sample 'observation) "obs-1")
  (error "bad ref lookup" sample))
(when (valid-gay-event? (make-gay-event 'bogus))
  (error "invalid kind accepted"))
(when (valid-gay-event? (make-gay-event 'protention #:color '((bad-key value))))
  (error "invalid color accepted"))
(display "gay-event-test ok\n")
